### ISSUE TITLE
hello,这里有个问题

### ISSUE THREAD

**Issue by meiqi1992** [lhr000lhr/SynxPlugin#3]
Resolved command path for "synx" is invalid.

Expanded GEM_PATH: /usr/bin

**Comment by meiqi1992** [comment]
resolvedCommand  一直为空

**Comment by meiqi1992** [comment]
xcode 7.2   osx 10.11.2

**Comment by lhr000lhr** [comment]
恩 ，需要先安装 synx。
打开 terminal   ， 输入

`gem install synx` 稍后我会完善一下 readme。

**Comment by meiqi1992** [comment]
![1](https://cloud.githubusercontent.com/assets/15257730/12226187/5243e76c-b853-11e5-84cb-c28fd6dc14cf.png)
已经安装了、按道理来说可以了 、可是还是不行

**Comment by lhr000lhr** [comment]
是`gem path` 问题 ，稍后我加上这个 修改默认的功能。(_^__^_) 嘻嘻……

**Comment by lhr000lhr** [comment]
已经更新了。可以试试！

**Comment by lhr000lhr** [comment]
在terminal 使用 

```
$ which synx
```

把得到的路径粘贴到插件的GEM_PATH即可。
